"use client";

import React, { useState } from "react";
import { 
  ShieldCheck, 
  Scale, 
  ChevronDown, 
  ChevronUp, 
  FileText,
  Info
} from "lucide-react";
import { cn } from "@/lib/utils";

interface EventRulesSectionProps {
  rules: string[];
}

interface ParsedRule {
  id: string;
  num: string;
  primaryText: string;
  detailedText?: string;
  isDetailed: boolean;
}

/**
 * Parse raw rule strings without arbitrary chopped ellipsis or artificial badges.
 */
function parseRuleItem(raw: string, index: number): ParsedRule {
  const clean = raw.trim();
  const num = String(index + 1).padStart(2, "0");
  const id = `regulation-${index + 1}`;

  // If rule has multiple sentences, split first sentence as primary directive
  const firstPeriod = clean.indexOf(". ");
  if (firstPeriod > 35 && firstPeriod < clean.length - 20) {
    return {
      id,
      num,
      primaryText: clean.slice(0, firstPeriod + 1).trim(),
      detailedText: clean.slice(firstPeriod + 2).trim(),
      isDetailed: true,
    };
  }

  // Self-contained statement
  return {
    id,
    num,
    primaryText: clean,
    isDetailed: false,
  };
}

export function EventRulesSection({ rules }: EventRulesSectionProps) {
  if (!rules || rules.length === 0) return null;

  const parsedRules: ParsedRule[] = rules
    .map((r) => (typeof r === "string" ? r.trim() : ""))
    .filter(Boolean)
    .map(parseRuleItem);

  if (parsedRules.length === 0) return null;

  const hasAnyDetails = parsedRules.some((r) => r.isDetailed);
  const [openIds, setOpenIds] = useState<string[]>([]);
  const [allExpanded, setAllExpanded] = useState<boolean>(false);

  const toggleItem = (id: string) => {
    setOpenIds((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const toggleAll = () => {
    if (allExpanded) {
      setOpenIds([]);
      setAllExpanded(false);
    } else {
      setOpenIds(parsedRules.filter((r) => r.isDetailed).map((r) => r.id));
      setAllExpanded(true);
    }
  };

  return (
    <section className="space-y-6">
      {/* ============================================================== */}
      {/* SECTION HEADER — Aligned with JDCOEM Platform Typography       */}
      {/* ============================================================== */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 pb-3 border-b border-slate-200">
        <div className="space-y-1">
          <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#E78023]">
            <ShieldCheck className="w-4 h-4 text-[#E78023]" />
            <span>Official Code of Conduct</span>
          </div>
          <h2 className="font-heading font-extrabold text-2xl sm:text-3xl text-[#17458F] uppercase tracking-tight">
            RULES &amp; GUIDELINES
          </h2>
          <p className="text-xs sm:text-sm text-slate-600 font-medium">
            Mandatory delegate directives, match protocols, and campus code of conduct.
          </p>
        </div>

        {/* Action Header Stats & Controls */}
        <div className="flex items-center gap-2 self-start sm:self-auto shrink-0">
          <span className="text-[11px] font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-blue-50 text-[#17458F] border border-blue-200/70 shadow-2xs flex items-center gap-1.5">
            <Scale className="w-3.5 h-3.5 text-[#17458F]" />
            <span>{parsedRules.length} Directives</span>
          </span>

          {hasAnyDetails && (
            <button
              type="button"
              onClick={toggleAll}
              className="text-[11px] font-bold uppercase tracking-wider px-3 py-1 rounded-full bg-slate-100 hover:bg-slate-200 text-slate-700 hover:text-[#17458F] border border-slate-200 transition-all cursor-pointer flex items-center gap-1 active:scale-95 min-h-[32px]"
              title={allExpanded ? "Collapse all rule notes" : "Expand all rule notes"}
            >
              {allExpanded ? (
                <>
                  <ChevronUp className="w-3.5 h-3.5" />
                  <span>Collapse All</span>
                </>
              ) : (
                <>
                  <ChevronDown className="w-3.5 h-3.5" />
                  <span>Expand Details</span>
                </>
              )}
            </button>
          )}
        </div>
      </div>

      {/* ============================================================== */}
      {/* 1. DESKTOP EXPERIENCE (hidden md:block)                        */}
      {/* Clean high-contrast card list without autogenerated badges     */}
      {/* ============================================================== */}
      <div className="hidden md:block space-y-3">
        {parsedRules.map((rule) => {
          const isOpen = openIds.includes(rule.id);
          const hasDetails = rule.isDetailed;

          return (
            <div
              key={rule.id}
              className={cn(
                "rounded-2xl border transition-all duration-200 bg-white shadow-2xs overflow-hidden group",
                isOpen
                  ? "border-[#17458F]/40 shadow-xs bg-gradient-to-r from-blue-50/20 via-white to-white"
                  : "border-slate-200/90 hover:border-slate-300 hover:shadow-xs"
              )}
            >
              <div
                onClick={() => hasDetails && toggleItem(rule.id)}
                className={cn(
                  "p-4 sm:p-5 flex items-center justify-between gap-4 transition-colors",
                  hasDetails ? "cursor-pointer" : "cursor-default"
                )}
                role={hasDetails ? "button" : undefined}
                tabIndex={hasDetails ? 0 : undefined}
                onKeyDown={(e) => {
                  if (hasDetails && (e.key === "Enter" || e.key === " ")) {
                    e.preventDefault();
                    toggleItem(rule.id);
                  }
                }}
                aria-expanded={hasDetails ? isOpen : undefined}
              >
                <div className="flex items-center gap-4 min-w-0 flex-1">
                  {/* Monospace Executive Number Badge */}
                  <div
                    className={cn(
                      "w-10 h-10 rounded-xl font-mono font-extrabold text-sm flex items-center justify-center shrink-0 border transition-all duration-200",
                      isOpen
                        ? "bg-[#17458F] text-white border-[#17458F] shadow-xs"
                        : "bg-blue-50 text-[#17458F] border-blue-200/80 group-hover:bg-[#17458F] group-hover:text-white group-hover:border-[#17458F]"
                    )}
                  >
                    {rule.num}
                  </div>

                  {/* Complete Statement — Clean, full sentence, zero truncation */}
                  <p className="text-[15px] font-semibold text-[#0F172A] leading-relaxed flex-1">
                    {rule.primaryText}
                  </p>
                </div>

                {/* Trailing Drawer Toggle (if elaboration exists) */}
                {hasDetails && (
                  <div className="shrink-0">
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        toggleItem(rule.id);
                      }}
                      className={cn(
                        "w-9 h-9 rounded-xl flex items-center justify-center text-slate-400 border border-slate-200/80 transition-all duration-200 cursor-pointer",
                        isOpen
                          ? "bg-[#E78023]/10 text-[#E78023] border-[#E78023]/30 rotate-180"
                          : "hover:bg-slate-100 hover:text-slate-700 group-hover:border-slate-300"
                      )}
                      aria-label={isOpen ? "Collapse elaboration" : "Expand elaboration"}
                    >
                      <ChevronDown className="w-4 h-4" />
                    </button>
                  </div>
                )}
              </div>

              {/* Elaboration Drawer */}
              {hasDetails && isOpen && (
                <div className="px-6 pb-5 pt-0 pl-[76px] text-sm text-slate-600 leading-relaxed font-medium animate-in fade-in-50 duration-200">
                  <div className="p-4 rounded-xl bg-slate-50 border border-slate-200/80 text-slate-700 space-y-1.5 shadow-2xs">
                    <div className="flex items-center gap-1.5 text-[11px] font-bold uppercase tracking-wider text-[#17458F]">
                      <Info className="w-3.5 h-3.5 text-[#17458F] shrink-0" />
                      <span>Detailed Protocol Specifics</span>
                    </div>
                    <p className="text-xs sm:text-sm leading-relaxed">{rule.detailedText}</p>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* ============================================================== */}
      {/* 2. MOBILE EXPERIENCE (block md:hidden)                         */}
      {/* Thumb-friendly, touch target >= 48px, compact & legible        */}
      {/* ============================================================== */}
      <div className="block md:hidden space-y-2.5">
        {parsedRules.map((rule) => {
          const isOpen = openIds.includes(rule.id);
          const hasDetails = rule.isDetailed;

          return (
            <div
              key={rule.id}
              className={cn(
                "rounded-2xl border transition-all duration-200 bg-white shadow-2xs overflow-hidden",
                isOpen
                  ? "border-l-4 border-l-[#17458F] border-t-slate-200 border-r-slate-200 border-b-slate-200 bg-slate-50/30"
                  : "border-slate-200"
              )}
            >
              <div
                onClick={() => hasDetails && toggleItem(rule.id)}
                className={cn(
                  "p-4 flex items-center justify-between gap-3 transition-colors min-h-[52px]",
                  hasDetails ? "cursor-pointer active:bg-slate-50" : "cursor-default"
                )}
                role={hasDetails ? "button" : undefined}
                tabIndex={hasDetails ? 0 : undefined}
                aria-expanded={hasDetails ? isOpen : undefined}
              >
                <div className="flex items-center gap-3 min-w-0 flex-1">
                  {/* Compact Monospace Pill */}
                  <span
                    className={cn(
                      "w-8 h-8 rounded-lg font-mono font-bold text-xs flex items-center justify-center shrink-0 border",
                      isOpen
                        ? "bg-[#17458F] text-white border-[#17458F]"
                        : "bg-blue-50 text-[#17458F] border-blue-200/80"
                    )}
                  >
                    {rule.num}
                  </span>

                  {/* Complete Statement — Always legible on phone */}
                  <p className="text-xs sm:text-sm font-semibold text-[#0F172A] leading-snug flex-1">
                    {rule.primaryText}
                  </p>
                </div>

                {hasDetails && (
                  <div className="shrink-0 min-w-[32px] min-h-[32px] flex items-center justify-center text-slate-400">
                    <ChevronDown
                      className={cn(
                        "w-4 h-4 transition-transform duration-200",
                        isOpen && "rotate-180 text-[#E78023]"
                      )}
                    />
                  </div>
                )}
              </div>

              {/* Mobile Drawer Details */}
              {hasDetails && isOpen && (
                <div className="px-4 pb-4 pt-0 pl-[52px] text-xs text-slate-600 leading-relaxed font-medium">
                  <div className="p-3 rounded-xl bg-white border border-slate-200 text-slate-700 shadow-2xs space-y-1">
                    <div className="flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-[#17458F]">
                      <FileText className="w-3 h-3 text-[#17458F] shrink-0" />
                      <span>Additional Instructions</span>
                    </div>
                    <p className="leading-relaxed">{rule.detailedText}</p>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}
